name: workflow_dispatch_action

on:
  workflow_dispatch:
    inputs:
      value:
        description: value
        required: true

jobs:
  echo:
    runs_on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ github.event.inputs.value }}